name: .NET CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: heckout do código
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
         dotnet-version: '8.0.117'


      - name: estaurar pacotes NuGet
        run: dotnet restore

      - name: Build do projeto
        run: dotnet build --no-restore --configuration Release

      - name: Executar testes
        run: dotnet test --no-build --verbosity normal
