name: .NET Core Build and Test

on:
  push:
  pull_request:  
  
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore Construes.sln

      - name: Build solution
        run: dotnet build Construes.sln --configuration ${{ matrix.configuration }} --no-restore

      - name: Run tests
        run: dotnet test Tests/Tests.csproj --configuration ${{ matrix.configuration }} --no-build --verbosity normal